apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-controller
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-controller
  template:
    metadata:
      labels:
        app: gateway-controller
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONTROLLER_CONFIG_MAP
          value: gateway-controller-configmap
        image: argoproj/gateway-controller:v0.13.0-rc
        imagePullPolicy: Always
        name: gateway-controller
      serviceAccountName: argo-events-sa
