apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-controller
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-controller
  template:
    metadata:
      labels:
        app: sensor-controller
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONTROLLER_CONFIG_MAP
          value: sensor-controller-configmap
        image: argoproj/sensor-controller:v0.13.0-rc
        imagePullPolicy: Always
        name: sensor-controller
      serviceAccountName: argo-events-sa
